backend:
  name: git-gateway
  branch: main

media_folder: "media/uploads"
public_folder: "/media/uploads"

collections:
  - name: "albums"
    label: "Photo Albums"
    folder: "media/albums"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Album Name", name: "title", widget: "string" }
      - { label: "Photos", name: "images", widget: "list", field: {label: Image, name: image, widget: image} }

  - name: "videos"
    label: "Video Albums"
    folder: "media/videos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Video Title", name: "title", widget: "string" }
      - { label: "Video File", name: "video", widget: "file" }
