backend:
  name: git-gateway
  branch: main

media_folder: "media/uploads"
public_folder: "/media/uploads"

collections:
  - name: "photo-albums"
    label: "Photo Albums"
    folder: "data/photo-albums"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Title", name: "title", widget: "string" }

      - { label: "Date", name: "date", widget: "datetime" }

      - label: "Photos"
        name: "photos"
        widget: "list"
        allow_add: true
        collapsed: false
        field:
          label: "Image"
          name: "image"
          widget: "image"

  - name: "video-albums"
    label: "Video Albums"
    folder: "data/video-albums"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Title", name: "title", widget: "string" }

      - { label: "Date", name: "date", widget: "datetime" }

      - label: "Videos"
        name: "videos"
        widget: "list"
        allow_add: true
        collapsed: false
        field:
          label: "Video URL"
          name: "video"
          widget: "string"
